import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
const SEARCH_URL=process.env.DUBIZZLE_URL||'https://www.dubizzle.com.eg/vehicles/cars-for-sale/';
const TELEGRAM_BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID=process.env.TELEGRAM_CHAT_ID;
const MAX_ITEMS=Number(process.env.MAX_ITEMS||60); if(!TELEGRAM_BOT_TOKEN||!TELEGRAM_CHAT_ID) throw new Error('Telegram config missing');
const dataDir=path.resolve('data'),seenPath=path.join(dataDir,'seen-dubizzle.json');await fs.mkdir(dataDir,{recursive:true});let seen=new Set();try{seen=new Set(JSON.parse(await fs.readFile(seenPath,'utf8')))}catch{}
function norm(s=''){return s.toLowerCase().replace(/[\-_]/g,' ').replace(/\s+/g,' ').trim()}
function targetCar(text=''){const t=norm(text);const years=(t.match(/(?:19|20)\d{2}/g)||[]).map(Number);const y=years.find(v=>v>=1990&&v<=2030);let name=null,min=0,max=2026,manual=false;
 if(/sunny|صني/.test(t)){name='Nissan Sunny';min=2016}
 else if(/aveo|افيو/.test(t)){name='Chevrolet Aveo';min=2016}
 else if(/(?:new\s*)?optra|اوبترا|أوبترا/.test(t)){name='Chevrolet New Optra';min=2016}
 else if(/accent\s*rb|اكسنت\s*(?:ار\s*بي|rb)/.test(t)){name='Hyundai Accent RB';min=2016}
 else if(/(?:\bbyd\b|بي\s*واي\s*دي).*(?:\bf3\b|اف\s*3)|(?:\bf3\b|اف\s*3).*(?:\bbyd\b|بي\s*واي\s*دي)/.test(t)){name='BYD F3';min=2021}
 else if(/elantra\s*hd|النترا\s*(?:اتش\s*دي|hd)/.test(t)){name='Hyundai Elantra HD';min=2017}
 else if(/verna|فيرنا/.test(t)){name='Hyundai Verna';min=2016}
 else if(/lanos|لانوس/.test(t)){name='Chevrolet Lanos';min=2016}
 else if(/arrizo\s*5|اريزو\s*(?:5|فايف)/.test(t)){name='Chery Arrizo 5';min=2019;manual=true}
 if(!name||!y||y<min||y>max)return null;if(manual&&!/manual|man\.?|مانيوال|يدوي/.test(t))return null;return{name,year:y}}
function isGiza(t=''){return /giza|الجيزة|جيزة|haram|هرم|dokki|دقي|mohandessin|مهندسين|agouza|عجوزة|6 october|october|اكتوبر|zayed|زايد|faisal|فيصل|imbaba|امبابة/i.test(t)}
function ageHours(text=''){const t=text.toLowerCase();if(/just now|today|الآن|اليوم/.test(t))return 0;let m=t.match(/(\d+)\s*(?:min|mins|minute|minutes|دقيقة|دقائق)/);if(m)return +m[1]/60;m=t.match(/(\d+)\s*(?:hr|hrs|hour|hours|ساعة|ساعات)/);if(m)return +m[1];if(/yesterday|أمس/.test(t))return 24;m=t.match(/(\d+)\s*(?:day|days|يوم|أيام)/);return m?+m[1]*24:null}function heat(a){return a<8?'🔥 HOT':a<16?'🟠 WARM':'🔵 COLD'}function looksNew(t=''){return /brand new|new car|zero km|0 km|زيرو|جديدة|جديد/i.test(t)}
async function sendTelegram(i){const text=['🚗 إعلان سيارة مستعملة جديد',`⚡ التصنيف: ${heat(i.age)}`,'🌐 المصدر: Dubizzle','',`🎯 ${i.target.name} ${i.target.year}`,`📌 ${i.title}`,`💰 السعر: ${i.priceText||'غير ظاهر'}`,`🕐 نازل من: ${i.listedAgo}`,i.location?`📍 المكان: ${i.location}`:'',`🔗 رابط الإعلان: ${i.url}`].filter(Boolean).join('\n');const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text,disable_web_page_preview:false})});if(!r.ok)throw new Error(`Telegram ${r.status}: ${await r.text()}`)}
const browser=await chromium.launch({headless:true}),context=await browser.newContext({locale:'en-US',userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36'}),page=await context.newPage();await page.goto(SEARCH_URL,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(3500);for(let i=0;i<6;i++){await page.mouse.wheel(0,2200);await page.waitForTimeout(600)}
const raw=await page.locator('a[href*="/ad/"]').evaluateAll(links=>{const out=[],used=new Set(),time=/(?:just now|today|yesterday|\d+\s*(?:min|mins|minute|minutes|hr|hrs|hour|hours|day|days)\s*ago|\d+\s*(?:دقيقة|دقائق|ساعة|ساعات|يوم|أيام)|الآن|اليوم|أمس)/i;for(const a of links){if(!a.href||!/ID\d+\.html/i.test(a.href))continue;const href=a.href.split('?')[0].split('#')[0],id=href.match(/ID(\d+)\.html/i)?.[1];if(!id||used.has(id))continue;used.add(id);let node=a,txt='';for(let i=0;i<6&&node;i++,node=node.parentElement){const c=(node.innerText||'').trim();if(c.length>5&&c.length<1800){txt=c;if(/EGP|ج\.م/i.test(c))break}}const lines=txt.split('\n').map(x=>x.trim()).filter(Boolean),priceText=lines.find(x=>/EGP|ج\.م/i.test(x))||'',listedAgo=lines.find(x=>time.test(x))||'',location=lines.find(x=>/giza|haram|dokki|mohandessin|agouza|october|zayed|faisal|imbaba|الجيزة|هرم|دقي|مهندسين|عجوزة|اكتوبر|زايد|فيصل|امبابة/i.test(x))||'',title=lines.find(x=>x!==priceText&&x!==listedAgo&&x!==location&&x.length>3)||a.innerText||'Dubizzle listing';out.push({id,href,title,priceText,listedAgo,location,rawText:txt})}return out});await page.close();let sent=0,targeted=0;for(const x of raw.slice(0,MAX_ITEMS)){const key=`Dubizzle:${x.id}`;if(seen.has(key))continue;const target=targetCar(`${x.title} ${x.rawText}`);if(!target)continue;targeted++;const age=ageHours(x.listedAgo);if(age===null||age>24)continue;if(x.location&&!isGiza(x.location))continue;if(looksNew(`${x.title} ${x.rawText}`))continue;await sendTelegram({url:x.href,title:x.title,priceText:x.priceText,listedAgo:x.listedAgo,location:x.location,age,target});seen.add(key);sent++}await fs.writeFile(seenPath,JSON.stringify([...seen].slice(-5000),null,2));console.log(`Dubizzle: collected=${raw.length}, targetCars=${targeted}, sent=${sent}`);await browser.close();